#importacion de las clases
from personaje import Personaje
from guerrero import Guerrero
from mago import Mago

#creacion de los personajes que pelean con cada clase
orco=Personaje("orcoll",100,100,27,39, False)
guerrero=Guerrero("Jule",100,100,25,40, False)
mago=Mago("Paco",100,110,28,35, False)

#metodo para probar que funciona el polimorfismo
def combate(personaje,enemigo):
    personaje.atacar(enemigo)

#main de peleas
print("======================================================================================================\n")
print("===================================================PRESENTEMOS A NUESTROS DOS PELEADORES!!===================================================\n")
print("(ORCOLL) Mi ataque sorpresa es un abrazo destructor de huesos\n")
print(orco.mostrar_estado())
print(guerrero.mostrar_estado())
print(mago.mostrar_estado())
print("============================================================================================================================================================\n")
print("===================================================    RECORDATORIO   =================================================================\n")
print("============================================================================================================================================================\n")
print("1. Por cada ataque se suma la experiencia (el valor que se suma depende del tipo de ataque 'ataque de fuerza o ataque sorpresa')\n")
print("2. El nivel aumenta en 1 cada 30XP (eso significa que en la experiencia se le resta 30)\n")
print("============================================================================================================================================================\n")
print("============================================================================================================================================================\n")
print("--------------------------------(PRESENTADOR) Que comience la batalla!--------------------------------\n")
print("============================================================================================================================================================\n")
print("====================================================== ROUND 1 ======================================================\n")
print(f"El primer ataque es de {guerrero.nombre}\n")
combate(guerrero,orco)
print("----------------------************************************************----------------------\n")
print(f"El segundo ataque es de {mago.nombre}\n")
combate(mago,guerrero)
print("----------------------************************************************----------------------\n")
print(f"El tercer ataque es de {orco.nombre}\n")
combate(orco,mago)
print("============================================================================================================================================================\n")
print("====================================================== ROUND 2 ======================================================\n")
print(f"El primer ataque es de {guerrero.nombre}\n")
combate(guerrero,orco)
print("----------------------************************************************----------------------\n")
print(f"El segundo ataque es de {mago.nombre}\n")
combate(mago,guerrero)
print("----------------------************************************************----------------------\n")
print(f"El tercer ataque es de {orco.nombre}\n")
combate(orco,mago)
print("============================================================================================================================================================\n")
print("QUE BATALLA, COMO VENIMOS\n")
print(guerrero.estoy_vivo())
print(mago.estoy_vivo())
print(orco.estoy_vivo())
print("============================================================================================================================================================\n")
print("====================================================== ROUND 3 ======================================================\n")
print(f"El primer ataque es de {guerrero.nombre}\n")
combate(guerrero,orco)
print("----------------------************************************************----------------------\n")
print(f"El segundo ataque es de {mago.nombre}\n")
combate(mago,guerrero)
print("----------------------************************************************----------------------\n")
print(f"El tercer ataque es de {orco.nombre}\n")
combate(orco,mago)
print("============================================================================================================================================================\n")
print("====================================================== ROUND 4 ======================================================\n")
print(f"El primer ataque es de {guerrero.nombre}\n")
combate(guerrero,orco)
print("----------------------************************************************----------------------\n")
print(f"El segundo ataque es de {mago.nombre}\n")
combate(mago,guerrero)
print("----------------------************************************************----------------------\n")
print(f"El tercer ataque es de {orco.nombre}\n")
combate(orco,mago)
print("============================================================================================================================================================\n")
print("QUE BATALLA, COMO VENIMOS\n")
print(guerrero.estoy_vivo())
print(mago.estoy_vivo())
print(orco.estoy_vivo())
print("============================================================================================================================================================\n")
print("====================================================== ROUND 5 ======================================================\n")
print(f"El primer ataque es de {guerrero.nombre}\n")
combate(guerrero,orco)
print("----------------------************************************************----------------------\n")
print(f"El segundo ataque es de {mago.nombre}\n")
combate(mago,guerrero)
print("----------------------************************************************----------------------\n")
print(f"El tercer ataque es de {orco.nombre}\n")
combate(orco,mago)
